### ISSUE TITLE
RFC: Lighter calendar grid lines

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#781]
Calendar grid lines should be lighter to look cleaner. Half-hour lines should be even lighter.

**Comment by KevinWu098** [comment]
```css
.rbc-timeslot-group {
    border-color: #808080;
    min-height: 25px;
}

.rbc-timeslot-group:nth-child(even) {
    /* border-color: #808080; */
    opacity: 50%;
}

.rbc-timeslot-group:nth-child(odd) {
}
```

Posting this here so i don't forget
